steps:
  # Install dependencies
  - name: node
    entrypoint: yarn
    args: ["install"]
  # Run custom commands
  - name: node
    entrypoint: yarn
    args: ["run", "build"]
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["-m", "cp", "-r", "build/*", "gs://www.react.matlau.co.uk"]
